// массив в праздниками и выходными
const defaultEvents = [
  {
    id: "1",
    name: "Выходной",
    description: "Новогодние каникулы",
    date: ["January/1/2000", "January/5/2000"],
    type: "holiday",
    everyYear: true,
  },
  {
    id: "2",
    name: "Выходной",
    description: "Рождество",
    date: "January/7/2000",
    type: "holiday",
    everyYear: true,
  },
  {
    id: "3",
    name: "Выходной",
    description: "День защитника Отечества",
    date: "February/23/2000",
    type: "holiday",
    everyYear: true,
  },
  {
    id: "4",
    name: "Выходной",
    description: "Международный жеский день",
    date: "March/8/2000",
    type: "holiday",
    everyYear: true,
  },
  {
    id: "5",
    name: "Выходной",
    description: "Праздник Весны и Труда;",
    date: "May/1/2000",
    type: "holiday",
    everyYear: true,
  },
  {
    id: "6",
    name: "Выходной",
    description: "День Победы",
    date: "May/9/2000",
    type: "holiday",
    everyYear: true,
  },
  {
    id: "7",
    name: "Выходной",
    description: "День России",
    date: "June/12/2000",
    type: "holiday",
    everyYear: true,
  },
  {
    id: "8",
    name: "Выходной",
    description: "День народного единства",
    date: "November/4/2000",
    type: "holiday",
    everyYear: true,
  },
];
